In [1]:
import pandas as pd

# this notebook is intended to ensure that the new structure search information that we used - which properly corrects for the percent coverage - has the desired properties compared to the old (2023) structure search hits data

In [19]:
data1 = pd.read_csv("summary_data/01B.structure_search_hits_0p90_coverage.csv")
data2 = pd.read_csv("../2024_09_13_GeO/summary_data/01B.structure_search_hits_0p90_coverage.csv")

In [20]:
print(len(data1), len(data2))

1372 1557

In [21]:
for uid in ["RPOB_MYCTU", "RPOC_MYCTU", "INHA_MYCTU", "KATG_MYCTU", "PNCA_MYCTU", "EMBB_MYCTU", "RSMG_MYCTU", "RS12_MYCTU", "GYRA_MYCTU"]:
    print(uid,
        data1.query("uid==@uid").pdb_id.values, 
        data2.query("uid==@uid").pdb_id.values
    )

RPOB_MYCTU ['6jcx'] ['6jcx']
RPOC_MYCTU ['6ee8'] ['6ee8']
INHA_MYCTU ['2b36'] ['2b36']
KATG_MYCTU ['4c51'] ['4c51']
PNCA_MYCTU ['3pl1'] ['3pl1']
EMBB_MYCTU ['7bvf'] ['7bvf']
RSMG_MYCTU ['1xdz'] ['1xdz']
RS12_MYCTU ['5mmj'] ['5mmj']
GYRA_MYCTU [] []

In [22]:
data2.query("uid=='RPOB_MYCTU'")

,Unnamed: 0,index,alignment_id,pdb_id,pdb_chain,uniprot_ac,uniprot_id,alignment_start,alignment_end,bitscore,...,coord_start,coord_end,uniprot_start,uniprot_end,uniprot_id_,overlap,mapping_index,grouped_segments,uid,percent_coverage
442,0,0,evsp|P9WGY9|RPOB_MYCTU/3-1177,6jcx,C,P9WGY9,RPOB_MYCTU,3,1177,0.1,...,27,78,27,1165,RPOB_MYCTU,1138,497,True,RPOB_MYCTU,0.966044

In [26]:
data1.sort_values("updated_coverage")

,Unnamed: 0,index,alignment_id,pdb_id,pdb_chain,uniprot_ac,uniprot_id,alignment_start,alignment_end,bitscore,...,coord_end,uniprot_start,uniprot_end,uniprot_id_,overlap,mapping_index,grouped_segments,uid,percent_coverage,updated_coverage
204,212,6,evsp|P9WFY7|TRMD_MYCTU/1-226,5zhl,A,P9WFY7,TRMD_MYCTU,1,226,0.2,...,227,1,227,TRMD_MYCTU,207,61,True,TRMD_MYCTU,0.900000,0.900
565,5,5,evsp|P0A738|MOAC_ECOLI/2-159,4pyd,C,P0A738,MOAC_ECOLI,2,159,0.1,...,157,4,157,MOAC_ECOLI,154,8,False,MOAC1_MYCTU,0.905882,0.900
988,8,8,evtr|E0TW95|E0TW95_BACPZ/4-177,5x11,B,E0TW95,E0TW95_BACPZ,4,177,0.1,...,180,1,180,E0TW95_BACPZ,171,27,True,P71704_MYCTU,0.950000,0.900
84,44,8,evtr|Q5SHB0|Q5SHB0_THET8/3-393,4uoc,A,Q5SHB0,Q5SHB0_THET8,3,393,0.2,...,394,1,394,Q5SHB0_THET8,391,26,False,CINAL_MYCTU,0.909302,0.900
720,2,2,evsp|P9WNK5|ESXB_MYCTU/1-100,3fav,C,P9WNK5,ESXB_MYCTU,1,100,0.1,...,90,1,90,ESXB_MYCTU,90,30,False,ESXB_MYCTU,0.900000,0.900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,0,0,evsp|P9WNK7|ESXA_MYCTU/1-95,1wa8,B,P9WNK7,ESXA_MYCTU,1,95,0.1,...,695,1,95,ESXA_MYCTU,95,27,False,ESXA_MYCTU,1.000000,1.000
936,0,0,evsp|P9WNK3|ESXH_MYCTU/1-96,2kg7,B,P9WNK3,ESXH_MYCTU,1,96,0.1,...,697,1,96,ESXH_MYCTU,96,16,False,ESXH_MYCTU,1.000000,1.000
22,0,0,evsp|P9WLD5|Y2302_MYCTU/1-80,2a7y,A,P9WLD5,Y2302_MYCTU,1,80,0.1,...,80,1,80,Y2302_MYCTU,80,0,False,Y2302_MYCTU,1.000000,1.000
760,0,0,evtr|A0R056|A0R056_MYCS2/1-139,6adq,H,A0R056,A0R056_MYCS2,1,139,0.1,...,139,1,139,A0R056_MYCS2,139,0,False,COX4_MYCTU,1.000000,1.000
443,309,309,evsp|P00441|SODC_HUMAN/11-151,6dtk,I,P00441,SODC_HUMAN,11,151,0.1,...,322,2,154,SODC_HUMAN,282,510,True,SODC_MYCTU,1.175000,1.175

In [16]:
data1.columns

Index(['Unnamed: 0', 'index', 'alignment_id', 'pdb_id', 'pdb_chain',
       'uniprot_ac', 'uniprot_id', 'alignment_start', 'alignment_end',
       'bitscore', 'e_value', 'resseq_start', 'resseq_end', 'coord_start',
       'coord_end', 'uniprot_start', 'uniprot_end', 'uniprot_id_', 'overlap',
       'mapping_index', 'grouped_segments', 'uid', 'percent_coverage',
       'updated_coverage'],
      dtype='object')

In [18]:
for uid in ["RECA_MYCTU", "IPYR_MYCTU"]:
    print(uid,
        data1.query("uid==@uid").pdb_id.values, 
        data2.query("uid==@uid").pdb_id.values
    )

RECA_MYCTU [] ['3cmt']
IPYR_MYCTU ['2uxs'] ['2uxs']