In [1]:
import pandas as pd
import glob
import numpy as np
from evcouplings.compare import DistanceMap, ClassicPDB
from copy import deepcopy
from scipy.stats import ks_2samp
import os
import matplotlib.pyplot as plt
import seaborn as sns

from evcouplings.visualize.pymol import (
    pymol_pair_lines, pymol_mapping
)

import warnings
warnings.filterwarnings("ignore")

In [2]:
!mkdir summary_data

### step 1: determine if any of the hits have at least 90% coverage overall - will later filter to see if these are coming from a single hit
d = pd.read_csv("../structure_search/output_structural_data_v3_2024.csv", index_col=0)
d = d.dropna(subset=["uid", "bitscore"])
d = d.fillna(0)

n_proteins = len(d.uid.unique())

# merge with correct lengths
proteome = pd.read_csv("../structure_search/H37Rv_proteome.csv")
print("total number of proteins in proteome", len(proteome))
l = proteome[["uid", "Length"]]
d = d.merge(l, on="uid", how="right")

print(f"hits for a total of {len(d.uid.unique())} proteins")
d.to_csv("summary_data/00.structure_search_hits.csv")

# Partition the datasets. Remember that each uid was searched for 3 different bitscores, 
# so make sure to account for uid redundancy
structure_hits_possible_90percent = d.query("percent_covered >= .9")
uids_possible_90percent = set(structure_hits_possible_90percent.uid)

structure_hits_less_than_90percent = d.query("percent_covered < 0.9 and num_hits > 0 and run_successful and not uid in @uids_possible_90percent")

all_structure_uids = uids_possible_90percent.union(set(structure_hits_less_than_90percent.uid))

no_hits = d.query("num_hits==0 and run_successful and not uid in @all_structure_uids")

print("Proteins with no structural hits", len(no_hits.uid.unique()))
print("proteins with a putative 90% hit", len(structure_hits_possible_90percent.uid.unique()))
print("Proteins with no 90% hits", len(structure_hits_less_than_90percent.uid.unique()))

mkdir: cannot create directory ‘summary_data’: File exists
total number of proteins in proteome 3993
hits for a total of 3993 proteins
Proteins with no structural hits 1009
proteins with a putative 90% hit 1571
Proteins with no 90% hits 1409

In [3]:
structure_hits_possible_90percent.query("uid=='RECA_MYCTU'")

Empty DataFrame
Columns: [uid, Length_x, run_successful, num_hits, num_hits_unfiltered, percent_covered, bitscore, Length_y]
Index: []

In [4]:
def select_best_distmap(df, length):
    
    for idx, row in df.iterrows():
        uid = row.uid
        bit = row.bitscore
        mapping_index = row.mapping_index
        
        dm_file = f"../structure_search/output/{uid}_b{bit}/compare/aux/{uid}_b{bit}_distmap_intra_{mapping_index}"
        
        if not os.path.isfile(dm_file+".npy"):
            continue
            
        dm = DistanceMap.from_file(dm_file)
        
        coverage = len(dm.residues_i) 
        if coverage >= 0.9*(length) and coverage <= length:
            #print("coverage", coverage, "length", length, dm_file)
            return idx, coverage
            
    return None, None

#### Determine if the coverage is coming from a single hit or multiple hits
#### If from a single hit, select the representative structure to use
#### Representative structures are taken from proteins with the same uniprot ID, if available, else take best hit

hit_information = []
uids_with_less_than_90percent = []

files_not_found = []
problem_uids = []

# Iterate through uids
for uid in structure_hits_possible_90percent.uid.unique():
    
    length = list(structure_hits_possible_90percent.query("uid==@uid").Length_x)[0]
    
    all_hits = pd.DataFrame()
    
    # Read in the structure hits for each bitscore and concatenate
    for bit in ["0.1", "0.2", "0.3", "1.2"]:
           # Read in the appropriate file
        try:
            s_hits = pd.read_csv(
                f"../structure_search/output/{uid}_b{bit}/compare/{uid}_b{bit}_structure_hits.csv"
            )
            s_hits["uid"] = uid
            s_hits["bitscore"] = bit
        except FileNotFoundError:
            files_not_found.append(uid)
            continue
        
        all_hits = pd.concat([all_hits, s_hits])
    #print(all_hits)
     
    # Take only hits with coverage > 90%
    all_hits["percent_coverage"] = all_hits.overlap / length
    all_hits = all_hits.reset_index()    
    top_hits = all_hits.query("percent_coverage >= .90")
    
    # guarantee that hits are sorted
    top_hits = top_hits.sort_values("e_value")
    #print(top_hits)
    
    if len(top_hits) ==0:
        uids_with_less_than_90percent.append(uid)
        continue
    
    # Take the hit with the highest similarity - if from MYCTU take that, else highest similarity
    self_hits = top_hits.query("uniprot_id==@uid")
    
    idx_to_keep = None
    
    if len(self_hits) > 0:
        idx_to_keep, coverage = select_best_distmap(self_hits, length)
        #print(idx_to_keep)
        
    if idx_to_keep is None:
        idx_to_keep, coverage = select_best_distmap(top_hits, length)
        
    if idx_to_keep is not None:
        top_hits.loc[idx_to_keep, "updated_coverage"] = coverage / length
        
        hit_information.append(top_hits.loc[idx_to_keep,:])
        
    elif idx_to_keep is None:
        problem_uids.append(uid)
        
hit_information = pd.DataFrame(hit_information)

print("Didn't find an individual structure hit with 90% coverage for", len(uids_with_less_than_90percent))
hit_information.to_csv("summary_data/01B.structure_search_hits_0p90_coverage.csv")

hit_information = pd.read_csv("summary_data/01B.structure_search_hits_0p90_coverage.csv", index_col=0)
print(len(hit_information), len(files_not_found), len(problem_uids))

Didn't find a single structure hit with 90% coverage for 0
1371 1704 200

In [5]:
uids_with_less_than_90percent += problem_uids

In [6]:
# ## Partition the dataset into alphafold and structure hits
# no_hits = d.query("not uid in @hit_information.uid")

no_hits = no_hits.drop_duplicates(["uid"])
print(len(no_hits))
no_hits.to_csv("summary_data/01A.structure_search_hits_no_hits.csv")

structure_hits_no_90percent = structure_hits_possible_90percent.query("uid in @uids_with_less_than_90percent")
structure_hits_less_than_90percent = pd.concat([structure_hits_no_90percent, structure_hits_less_than_90percent])
structure_hits_less_than_90percent = structure_hits_less_than_90percent.drop_duplicates(["uid"])
print(len(structure_hits_less_than_90percent))
structure_hits_less_than_90percent.to_csv("summary_data/01C.structure_search_hits_less_than_90_percent.csv")

1009
1609

## Generate distancemaps for alphafold predictions

In [10]:
hit_information = pd.read_csv("summary_data/01A.structure_search_hits_no_hits.csv", index_col=0)
hit_information2 = pd.read_csv("summary_data/01C.structure_search_hits_less_than_90_percent.csv", index_col=0)
hit_information = pd.concat([hit_information, hit_information2])

id_mapping = pd.read_csv("../GeO_2021_09_15//summary_data/h37rv_gene_ids_to_uniprot_ids.csv", index_col=0)
hit_information = hit_information.merge(id_mapping[["Entry name", "Entry", "rv"]], how="left", left_on="uid", right_on="Entry name")

alphafold_filtering_information = []

! mkdir ../alphafold/UP000001584_83332_MYCTU_v4_b70_filtered
! mkdir alphafold_distmaps

skip = False

for idx, row in hit_information.iterrows():

    uid = row.uid
    entry = row.Entry
    
    if skip and os.path.isfile(f"alphafold_distmaps/{entry}.csv"):
        print(uid, "already completed")
        continue
        
    print("running", uid)
    
    try:
        structure = ClassicPDB.from_file(f"../alphafold/UP000001584_83332_MYCTU_v4/AF-{entry}-F1-model_v4.pdb")
    except: 
        print("no file for ", entry)
        continue

    chain = structure.get_chain("A")

    current_pdb_low_b_factor = list(chain.coords.query("b_factor < 70").residue_index)
    num_residues_initial = len(chain.coords.residue_index.unique())
    
    residues_to_keep = chain.coords.query("b_factor >= 70").residue_index
    print(num_residues_initial, len(residues_to_keep))
    chain2 = chain.filter_positions(residues_to_keep)
    dm = DistanceMap.from_coords(chain2)

    dm.to_file(f"alphafold_distmaps/{entry}")

    chain2.to_file(open(f"../alphafold/UP000001584_83332_MYCTU_v4_b70_filtered/AF-{entry}-F1-model_v4_beta70filtered.pdb", "w"))
    
    alphafold_filtering_information.append([entry, uid, num_residues_initial, len(residues_to_keep.unique())])

alphafold_filtering_information = pd.DataFrame(alphafold_filtering_information, columns=["entry", "uid", "residues_initial", "residues_filtered"])

alphafold_filtering_information.to_csv("summary_data/alphafold_filtering_information.csv")

mkdir: cannot create directory ‘../alphafold/UP000001584_83332_MYCTU_v4_b70_filtered’: File exists
mkdir: cannot create directory ‘alphafold_distmaps’: File exists
running Y876_MYCTU
559 2280
running Y2076_MYCTU
83 50
running Y037_MYCTU
441 2945
running Y1995_MYCTU
255 1541
running Y2012_MYCTU
164 1066

KeyboardInterrupt:

In [11]:
alphafold_filtered = pd.read_csv("summary_data/alphafold_filtering_information.csv")
print(len(alphafold_filtered))
alphafold_filtered.query("residues_filtered > 0")

2614

      Unnamed: 0   entry           uid  residues_initial  residues_filtered
0              0  P9WKR5    Y876_MYCTU               559                315
1              1  P9WLL3   Y2076_MYCTU                83                  6
2              2  P9WJY1    Y037_MYCTU               441                402
3              3  P9WLP3   Y1995_MYCTU               255                192
4              4  P9WLM3   Y2012_MYCTU               164                136
...          ...     ...           ...               ...                ...
2609        2609  I6Y9H2  I6Y9H2_MYCTU               185                158
2610        2610  L0TB61  L0TB61_MYCTU               324                271
2611        2611  L7N662  L7N662_MYCTU               485                456
2612        2612  O53340  O53340_MYCTU               340                339
2613        2613  P96354  P96354_MYCTU               415                364

[2548 rows x 5 columns]

## Filter the EBR and mappability regions from all distance maps

In [12]:
!mkdir input
!cp ../2023_02_23_benchmark/input/AF7_H37Rv_FeatureLevelAnalysis.EBR_And_Pmap.tsv input
!cp ../2023_02_23_benchmark/input/EBR.csv input
!cp ../2023_02_23_benchmark/input/S7-seq-attributes.csv input
!cp ../GeO_2021_09_21/summary_data/h37rv_gene_ids_to_uniprot_ids.csv input

In [13]:
## Get a list of proteins with poor EBR and/or mappability

mappability = pd.read_csv("input/AF7_H37Rv_FeatureLevelAnalysis.EBR_And_Pmap.tsv", sep="\t")
mappability = mappability.query('Feature == "CDS"')

print("all proteins in Marin et al", len(mappability))
print("after filtering", len(mappability.query("Mean_EBR_36CI >= .9 and Mean_PileupMapScore_K50_E4 >= .9")))

proteins_to_keep = mappability.query("Mean_EBR_36CI >= .9 and Mean_PileupMapScore_K50_E4 >= .9")

all proteins in Marin et al 4031
after filtering 3844

In [14]:
## Combined file of structure hits and alphafold hits
## filter for EBR, mappability

In [15]:
alphafold_hits = pd.read_csv("summary_data/01A.structure_search_hits_no_hits.csv", index_col=0)
alphafold_hits["set"] = "setA"

structure_hits = pd.read_csv("summary_data/01B.structure_search_hits_0p90_coverage.csv", index_col=0)
structure_hits["set"] = "setB"

structure_hits2 = pd.read_csv("summary_data/01C.structure_search_hits_less_than_90_percent.csv", index_col=0)
structure_hits2["set"] = "setA"

all_hits = pd.concat([alphafold_hits, structure_hits, structure_hits2])

# Get the H37rv locus tag
id_mapping = pd.read_csv("input/h37rv_gene_ids_to_uniprot_ids.csv", index_col=0)
all_hits = all_hits.merge(id_mapping[["Entry name", "Entry", "rv"]], how='left', left_on="uid", right_on="Entry name")

# Filtering
all_hits = all_hits.query("rv in @proteins_to_keep.H37rv_GeneID")
all_hits.query("uid=='EMBB_MYCTU'")

,uid,Length_x,run_successful,num_hits,num_hits_unfiltered,percent_covered,bitscore,Length_y,set,index,...,uniprot_end,uniprot_id_,overlap,mapping_index,grouped_segments,percent_coverage,updated_coverage,Entry name,Entry,rv
1802,EMBB_MYCTU,NaN,NaN,NaN,NaN,NaN,0.1,NaN,setB,0.0,...,1098.0,EMBB_MYCTU,1054.0,1.0,True,0.959927,0.959927,EMBB_MYCTU,P9WNL7,Rv3795

In [16]:
# Prepare a list of sites in each gene that can be mapped
genome_position_to_gene = pd.read_csv("../../databases/genome_position_to_gene_with_codons.csv")
genome_position_to_gene = genome_position_to_gene.drop("ebr", axis=1)

# Ensure that we've accurately filtered positions from Marin et al
ebr = pd.read_csv(
    "input/EBR.csv", index_col=0
)
genome_position_to_gene = genome_position_to_gene.merge(ebr, left_on="i", right_on="position", how="left")

# Accurately filter the positions from Modlin et al
modlin = pd.read_csv("input/S7-seq-attributes.csv")[["rv_position", "blindspot"]]
blindspots = modlin.query("blindspot==1")
blindspot_list = list(blindspots.rv_position)
genome_position_to_gene = genome_position_to_gene.merge(modlin, left_on="i", right_on="rv_position", how="left")

genome_position_to_gene.to_csv("input/gene_positions_included.csv")

In [17]:
# Remove proteins with no alphafold residues
alphafold_filtering = pd.read_csv("summary_data/alphafold_filtering_information.csv", index_col=0)
no_coverage = alphafold_filtering.query("residues_filtered==0").uid

all_hits = all_hits.query("not uid in @no_coverage")

## Iterate through all distance maps, create filtered version, save to the same directory

In [41]:
!mkdir filtered_distmaps

mkdir: cannot create directory ‘filtered_distmaps’: File exists

In [18]:
# Quick patch - the alphafold structures don't have a chain_index in their output distancemap.csv files
# So, let's read them and set the chain id to the same as the coord id

for idx, row in all_hits.iterrows():
    entry = row["Entry"]

    if row.set=='setA': #alphafold distancemap
        try:
            data = pd.read_csv(f"alphafold_distmaps/{entry}.csv", index_col=0)
            data.chain_index = data.coord_id
            data.to_csv(f"alphafold_distmaps/{entry}.csv")
        except:
            continue

In [19]:
def filter_distmatrix(dm, residues_to_filter):
    print("length of dist matrix before filtering", len(dm.residues_i))
    dm.residues_i.reset_index(drop=True, inplace=True)
    dm.residues_i = dm.residues_i.query("id not in @residues_to_filter")
    
    print("length of dist matrix after filtering", len(dm.residues_i))
    keep_indices = np.array([x for x in dm.residues_i.index])
    dm.dist_matrix = dm.dist_matrix[keep_indices,:][:, keep_indices]
    
    return dm

In [21]:
! mkdir output
! mkdir filtered_distmaps
excluded_ids = []
skip=True

all_hits["filtered_length"] = np.nan

for idx, row in all_hits.iterrows():
    uid = row.uid
    
#     if not uid=='EMBB_MYCTU':
#         continue
    
    rv = row.rv
    entry = row["Entry"]
    #print(entry)
    os.system(f"mkdir output/{uid}")   
    
    if skip and os.path.isfile(f"filtered_distmaps/{entry}.csv"):
        continue
        
    if row.set=='setA': #alphafold distancemap
        try:
            dm = DistanceMap.from_file(f"alphafold_distmaps/{entry}")
        except:
            print("no alphafold distance map", entry)
            excluded_ids.append(uid)
            continue
            
    elif row.set=='setB': #structure distancemap
    
        bit = row.bitscore
        mapping_index = int(row.mapping_index)
        prefix = f"{uid}_b{bit}_m{mapping_index}"

        # Read in the distance map
        try:
            dm = DistanceMap.from_file(f"../structure_search/output/{uid}_b{bit}/compare/aux/{uid}_b{bit}_distmap_intra_{mapping_index}")
        except:
            print("no distance map", f"../structure_search/output/{uid}_b{bit}/compare/aux/{uid}_b{bit}_distmap_intra_{mapping_index}")
            continue
    
    print(row.set, dm.dist_matrix.shape)
    
    current_locus_mappability = genome_position_to_gene.query("locus==@rv")
    current_locus_unmappable = current_locus_mappability.query("blindspot==1 or EBR < 0.9").codon.astype(int).astype(str).unique()
    df_unmappable = pd.DataFrame(data=current_locus_unmappable, columns=["i"])
    df_unmappable.to_csv(f"output/{uid}/unmappable_residues.csv")  
    
    if len(current_locus_unmappable) == 0:
        pass
    elif len(current_locus_unmappable) < len(dm.residues_i):
        print(f"Filtering {len(current_locus_unmappable)} from distmatrix with shape {dm.dist_matrix.shape}")
        dm = filter_distmatrix(dm, current_locus_unmappable)
        print("Result has shape", dm.dist_matrix.shape)
    else:
        print("all the positions are unmappable", uid)
        excluded_ids.append(uid)
        continue
        
    all_hits.loc[idx, "filtered_length"] = len(dm.residues_i)
        
    
    dm.to_file(f"filtered_distmaps/{entry}")
    
    #break

mkdir: cannot create directory ‘output’: File exists

mkdir: cannot create directory ‘output/Y876_MYCTU’: File exists

setA (315, 315)
setA (6, 6)
setA (402, 402)
setA (192, 192)
Filtering 3 from distmatrix with shape (192, 192)
length of dist matrix before filtering 192
length of dist matrix after filtering 189
Result has shape (189, 189)
setA (136, 136)
setA (248, 248)
setA (372, 372)
setA (256, 256)
setA (263, 263)
Filtering 2 from distmatrix with shape (263, 263)
length of dist matrix before filtering 263
length of dist matrix after filtering 261
Result has shape (261, 261)
setA (78, 78)
setA (150, 150)
setA (326, 326)
setA (88, 88)
setA (127, 127)
setA (253, 253)
setA (138, 138)
setA (55, 55)
setA (111, 111)
setA (56, 56)
setA (341, 341)
setA (328, 328)
setA (112, 112)
setA (99, 99)
setA (918, 918)
setA (181, 181)
setA (325, 325)
setA (352, 352)
setA (508, 508)
setA (60, 60)
setA (232, 232)
setA (229, 229)
setA (422, 422)
Filtering 88 from distmatrix with shape (422, 422)
length of dist matrix before filtering 422
length of dist matrix after filtering 354
Result has shape (354, 354)
setA (532, 532)
setA (348, 348)
Filtering 2 from distmatrix with shape (348, 348)
length of dist matrix before filtering 348
length of dist matrix after filtering 346
Result has shape (346, 346)
setA (237, 237)
setA (230, 230)
setA (164, 164)
Filtering 18 from distmatrix with shape (164, 164)
length of dist matrix before filtering 164
length of dist matrix after filtering 162
Result has shape (162, 162)
setA (338, 338)
Filtering 8 from distmatrix with shape (338, 338)
length of dist matrix before filtering 338
length of dist matrix after filtering 331
Result has shape (331, 331)
setA (223, 223)
setA (6, 6)
setA (50, 50)
setA (191, 191)
setA (540, 540)
setA (398, 398)
setA (159, 159)
setA (227, 227)
setA (168, 168)
setA (444, 444)
Filtering 34 from distmatrix with shape (444, 444)
length of dist matrix before filtering 444
length of dist matrix after filtering 410
Result has shape (410, 410)
setA (96, 96)
setA (66, 66)
setA (139, 139)
setA (237, 237)
Filtering 2 from distmatrix with shape (237, 237)
length of dist matrix before filtering 237
length of dist matrix after filtering 235
Result has shape (235, 235)
setA (318, 318)
Filtering 35 from distmatrix with shape (318, 318)
length of dist matrix before filtering 318
length of dist matrix after filtering 283
Result has shape (283, 283)
setA (565, 565)
setA (180, 180)
setA (84, 84)
setA (478, 478)
setA (452, 452)
Filtering 16 from distmatrix with shape (452, 452)
length of dist matrix before filtering 452
length of dist matrix after filtering 437
Result has shape (437, 437)
setA (441, 441)
setA (139, 139)
setA (105, 105)
setA (161, 161)
setA (271, 271)
setA (20, 20)
setA (495, 495)
setA (188, 188)
setA (469, 469)
setA (76, 76)
setA (146, 146)
setA (154, 154)
setA (171, 171)
setA (232, 232)
setA (99, 99)
setA (737, 737)
setA (39, 39)
setA (229, 229)
setA (82, 82)
setA (107, 107)
setA (580, 580)
setA (253, 253)
setA (110, 110)
setA (264, 264)
setA (280, 280)
Filtering 62 from distmatrix with shape (280, 280)
length of dist matrix before filtering 280
length of dist matrix after filtering 249
Result has shape (249, 249)
setA (172, 172)
setA (134, 134)
setA (92, 92)
setA (53, 53)
setA (270, 270)
setA (67, 67)
setA (145, 145)
setA (435, 435)
setA (191, 191)
setA (727, 727)
setA (278, 278)
setA (380, 380)
setA (232, 232)
Filtering 63 from distmatrix with shape (232, 232)
length of dist matrix before filtering 232
length of dist matrix after filtering 232
Result has shape (232, 232)
setA (244, 244)
setA (402, 402)
setA (225, 225)
Filtering 1 from distmatrix with shape (225, 225)
length of dist matrix before filtering 225
length of dist matrix after filtering 224
Result has shape (224, 224)
setA (194, 194)
setA (141, 141)
setA (106, 106)
setA (163, 163)
setA (192, 192)
setA (139, 139)
setA (259, 259)
setA (156, 156)
setA (394, 394)
setA (401, 401)
setA (242, 242)
setA (197, 197)
setA (583, 583)
setA (150, 150)
setA (178, 178)
setA (395, 395)
setA (323, 323)
setA (231, 231)
setA (97, 97)
setA (846, 846)
setA (51, 51)
setA (483, 483)
setA (376, 376)
setA (395, 395)
setA (388, 388)
setA (285, 285)
setA (465, 465)
setA (584, 584)
Filtering 2 from distmatrix with shape (584, 584)
length of dist matrix before filtering 584
length of dist matrix after filtering 584
Result has shape (584, 584)
setA (30, 30)
setA (192, 192)
setA (316, 316)
setA (382, 382)
setA (87, 87)
setA (414, 414)
Filtering 1 from distmatrix with shape (414, 414)
length of dist matrix before filtering 414
length of dist matrix after filtering 413
Result has shape (413, 413)
setA (521, 521)
Filtering 275 from distmatrix with shape (521, 521)
length of dist matrix before filtering 521
length of dist matrix after filtering 246
Result has shape (246, 246)
setA (338, 338)
setA (817, 817)
setA (112, 112)
setA (352, 352)
Filtering 3 from distmatrix with shape (352, 352)
length of dist matrix before filtering 352
length of dist matrix after filtering 349
Result has shape (349, 349)
setA (120, 120)
Filtering 2 from distmatrix with shape (120, 120)
length of dist matrix before filtering 120
length of dist matrix after filtering 118
Result has shape (118, 118)
setA (893, 893)
Filtering 3 from distmatrix with shape (893, 893)
length of dist matrix before filtering 893
length of dist matrix after filtering 890
Result has shape (890, 890)
setA (617, 617)
setA (250, 250)
setA (145, 145)
setA (150, 150)
setA (174, 174)
setA (233, 233)
setA (126, 126)
Filtering 64 from distmatrix with shape (126, 126)
length of dist matrix before filtering 126
length of dist matrix after filtering 98
Result has shape (98, 98)
setA (495, 495)
Filtering 110 from distmatrix with shape (495, 495)
length of dist matrix before filtering 495
length of dist matrix after filtering 388
Result has shape (388, 388)
setA (490, 490)
setA (29, 29)
all the positions are unmappable INIB_MYCTU
setA (92, 92)
setA (958, 958)
Filtering 410 from distmatrix with shape (958, 958)
length of dist matrix before filtering 958
length of dist matrix after filtering 572
Result has shape (572, 572)
setA (236, 236)
setA (546, 546)
setA (465, 465)
setA (82, 82)
setA (223, 223)
setA (250, 250)
Filtering 4 from distmatrix with shape (250, 250)
length of dist matrix before filtering 250
length of dist matrix after filtering 246
Result has shape (246, 246)
setA (193, 193)
setA (835, 835)
setA (383, 383)
setA (109, 109)
setA (1, 1)
setA (297, 297)
setA (118, 118)
Filtering 2 from distmatrix with shape (118, 118)
length of dist matrix before filtering 118
length of dist matrix after filtering 118
Result has shape (118, 118)
setA (436, 436)
setA (382, 382)
setA (134, 134)
setA (277, 277)
setA (165, 165)
setA (253, 253)
setA (197, 197)
setA (208, 208)
setA (551, 551)
setA (90, 90)
setA (74, 74)
setA (141, 141)
setA (141, 141)
setA (313, 313)
setA (132, 132)
setA (874, 874)
Filtering 77 from distmatrix with shape (874, 874)
length of dist matrix before filtering 874
length of dist matrix after filtering 841
Result has shape (841, 841)
setA (439, 439)
Filtering 44 from distmatrix with shape (439, 439)
length of dist matrix before filtering 439
length of dist matrix after filtering 418
Result has shape (418, 418)
setA (102, 102)
setA (7, 7)
setA (675, 675)
setA (70, 70)
setA (112, 112)
setA (293, 293)
setA (115, 115)
Filtering 2 from distmatrix with shape (115, 115)
length of dist matrix before filtering 115
length of dist matrix after filtering 113
Result has shape (113, 113)
setA (366, 366)
Filtering 12 from distmatrix with shape (366, 366)
length of dist matrix before filtering 366
length of dist matrix after filtering 362
Result has shape (362, 362)
setA (167, 167)
setA (117, 117)
setA (107, 107)
setA (308, 308)
Filtering 2 from distmatrix with shape (308, 308)
length of dist matrix before filtering 308
length of dist matrix after filtering 306
Result has shape (306, 306)
setA (120, 120)
setA (182, 182)
setA (138, 138)
setA (94, 94)
setA (531, 531)
setA (400, 400)
setA (370, 370)
setA (369, 369)
setA (126, 126)
setA (207, 207)
setA (145, 145)
setA (112, 112)
setA (163, 163)
setA (91, 91)
setA (253, 253)
setA (100, 100)
setA (136, 136)
setA (172, 172)
setA (173, 173)
setA (44, 44)
setA (247, 247)
Filtering 5 from distmatrix with shape (247, 247)
length of dist matrix before filtering 247
length of dist matrix after filtering 242
Result has shape (242, 242)
setA (258, 258)
Filtering 1 from distmatrix with shape (258, 258)
length of dist matrix before filtering 258
length of dist matrix after filtering 257
Result has shape (257, 257)
setA (424, 424)
Filtering 2 from distmatrix with shape (424, 424)
length of dist matrix before filtering 424
length of dist matrix after filtering 422
Result has shape (422, 422)
setA (204, 204)
setA (299, 299)
setA (98, 98)
setA (312, 312)
Filtering 38 from distmatrix with shape (312, 312)
length of dist matrix before filtering 312
length of dist matrix after filtering 274
Result has shape (274, 274)
setA (125, 125)
setA (71, 71)
setA (144, 144)
setA (233, 233)
setA (39, 39)
setA (60, 60)
setA (153, 153)
setA (617, 617)
setA (64, 64)
Filtering 15 from distmatrix with shape (64, 64)
length of dist matrix before filtering 64
length of dist matrix after filtering 64
Result has shape (64, 64)
setA (206, 206)
Filtering 10 from distmatrix with shape (206, 206)
length of dist matrix before filtering 206
length of dist matrix after filtering 200
Result has shape (200, 200)
setA (316, 316)
setA (113, 113)
setA (96, 96)
setA (282, 282)
Filtering 2 from distmatrix with shape (282, 282)
length of dist matrix before filtering 282
length of dist matrix after filtering 280
Result has shape (280, 280)
setA (90, 90)
setA (838, 838)
setA (513, 513)
setA (356, 356)
setA (77, 77)
setA (323, 323)
setA (327, 327)
setA (108, 108)
setA (126, 126)
setA (305, 305)
setA (875, 875)
Filtering 1 from distmatrix with shape (875, 875)
length of dist matrix before filtering 875
length of dist matrix after filtering 874
Result has shape (874, 874)
setA (894, 894)
setA (537, 537)
Filtering 162 from distmatrix with shape (537, 537)
length of dist matrix before filtering 537
length of dist matrix after filtering 376
Result has shape (376, 376)
setA (509, 509)
Filtering 62 from distmatrix with shape (509, 509)
length of dist matrix before filtering 509
length of dist matrix after filtering 459
Result has shape (459, 459)
setA (229, 229)
setA (84, 84)
setA (385, 385)
all the positions are unmappable PG05_MYCTU
setA (490, 490)
setA (642, 642)
setA (151, 151)
setA (118, 118)
setA (175, 175)
Filtering 69 from distmatrix with shape (175, 175)
length of dist matrix before filtering 175
length of dist matrix after filtering 161
Result has shape (161, 161)
setA (453, 453)
Filtering 287 from distmatrix with shape (453, 453)
length of dist matrix before filtering 453
length of dist matrix after filtering 169
Result has shape (169, 169)
setA (118, 118)
setA (888, 888)
Filtering 17 from distmatrix with shape (888, 888)
length of dist matrix before filtering 888
length of dist matrix after filtering 871
Result has shape (871, 871)
setA (895, 895)
setA (874, 874)
setA (516, 516)
setA (832, 832)
setA (618, 618)
setA (1523, 1523)
setA (275, 275)
setA (402, 402)
Filtering 1 from distmatrix with shape (402, 402)
length of dist matrix before filtering 402
length of dist matrix after filtering 401
Result has shape (401, 401)
setA (57, 57)
setA (305, 305)
setA (169, 169)
Filtering 49 from distmatrix with shape (169, 169)
length of dist matrix before filtering 169
length of dist matrix after filtering 169
Result has shape (169, 169)
setA (436, 436)
setA (466, 466)
setA (391, 391)
setA (200, 200)
setA (255, 255)
setA (111, 111)
setA (245, 245)
setA (40, 40)
setA (102, 102)
setA (116, 116)
setA (168, 168)
setA (91, 91)
setA (286, 286)
Filtering 258 from distmatrix with shape (286, 286)
length of dist matrix before filtering 286
length of dist matrix after filtering 274
Result has shape (274, 274)
setA (309, 309)
setA (22, 22)
setA (873, 873)
setA (246, 246)
setA (107, 107)
setA (145, 145)
setA (92, 92)
setA (140, 140)
setA (174, 174)
setA (156, 156)
setA (25, 25)
Filtering 2 from distmatrix with shape (25, 25)
length of dist matrix before filtering 25
length of dist matrix after filtering 25
Result has shape (25, 25)
setA (96, 96)
setA (425, 425)
Filtering 117 from distmatrix with shape (425, 425)
length of dist matrix before filtering 425
length of dist matrix after filtering 372
Result has shape (372, 372)
setA (717, 717)
setA (222, 222)
setA (486, 486)
setA (448, 448)
Filtering 1 from distmatrix with shape (448, 448)
length of dist matrix before filtering 448
length of dist matrix after filtering 447
Result has shape (447, 447)
setA (490, 490)
setA (296, 296)
setA (417, 417)
setA (294, 294)
setA (322, 322)
setA (1, 1)
setA (371, 371)
Filtering 7 from distmatrix with shape (371, 371)
length of dist matrix before filtering 371
length of dist matrix after filtering 364
Result has shape (364, 364)
setA (790, 790)
setA (179, 179)
setA (91, 91)
setA (48, 48)
setA (209, 209)
setA (164, 164)
setA (227, 227)
setA (167, 167)
Filtering 1 from distmatrix with shape (167, 167)
length of dist matrix before filtering 167
length of dist matrix after filtering 167
Result has shape (167, 167)
setA (230, 230)
setA (319, 319)
setA (36, 36)
setA (252, 252)
setA (301, 301)
Filtering 38 from distmatrix with shape (301, 301)
length of dist matrix before filtering 301
length of dist matrix after filtering 282
Result has shape (282, 282)
setA (972, 972)
setA (95, 95)
setA (117, 117)
setA (85, 85)
setA (164, 164)
setA (691, 691)
setA (128, 128)
setA (207, 207)
setA (233, 233)
setA (252, 252)
setA (87, 87)
setA (485, 485)
setA (399, 399)
setA (396, 396)
setA (127, 127)
setA (264, 264)
setA (393, 393)
setA (106, 106)
setA (178, 178)
Filtering 24 from distmatrix with shape (178, 178)
length of dist matrix before filtering 178
length of dist matrix after filtering 178
Result has shape (178, 178)
setA (130, 130)
setA (820, 820)
Filtering 11 from distmatrix with shape (820, 820)
length of dist matrix before filtering 820
length of dist matrix after filtering 809
Result has shape (809, 809)
setA (497, 497)
Filtering 1 from distmatrix with shape (497, 497)
length of dist matrix before filtering 497
length of dist matrix after filtering 496
Result has shape (496, 496)
setA (296, 296)
setA (68, 68)
setA (185, 185)
setA (223, 223)
setA (250, 250)
setA (165, 165)
setA (389, 389)
setA (160, 160)
setA (52, 52)
setA (124, 124)
setA (417, 417)
setA (226, 226)
setA (105, 105)
setA (310, 310)
setA (202, 202)
setA (140, 140)
setA (183, 183)
setA (42, 42)
Filtering 1 from distmatrix with shape (42, 42)
length of dist matrix before filtering 42
length of dist matrix after filtering 42
Result has shape (42, 42)
setA (361, 361)
setA (125, 125)
setA (629, 629)
setA (54, 54)
setA (911, 911)
Filtering 1 from distmatrix with shape (911, 911)
length of dist matrix before filtering 911
length of dist matrix after filtering 910
Result has shape (910, 910)
setA (220, 220)
setA (196, 196)
setA (286, 286)
setA (237, 237)
setA (37, 37)
setA (502, 502)
Filtering 374 from distmatrix with shape (502, 502)
length of dist matrix before filtering 502
length of dist matrix after filtering 175
Result has shape (175, 175)
setA (46, 46)
setA (422, 422)
Filtering 7 from distmatrix with shape (422, 422)
length of dist matrix before filtering 422
length of dist matrix after filtering 415
Result has shape (415, 415)
setA (101, 101)
setA (295, 295)
setA (34, 34)
setA (127, 127)
Filtering 24 from distmatrix with shape (127, 127)
length of dist matrix before filtering 127
length of dist matrix after filtering 127
Result has shape (127, 127)
setA (7, 7)
setA (602, 602)
Filtering 316 from distmatrix with shape (602, 602)
length of dist matrix before filtering 602
length of dist matrix after filtering 311
Result has shape (311, 311)
setA (487, 487)
setA (188, 188)
setA (57, 57)
setA (176, 176)
setA (55, 55)
setA (294, 294)
setA (341, 341)
Filtering 2 from distmatrix with shape (341, 341)
length of dist matrix before filtering 341
length of dist matrix after filtering 339
Result has shape (339, 339)
setA (190, 190)
setA (142, 142)
setA (277, 277)
setA (225, 225)
setA (350, 350)
setA (139, 139)
setA (283, 283)
setA (351, 351)
setA (326, 326)
setA (71, 71)
setA (145, 145)
setA (99, 99)
setA (286, 286)
Filtering 24 from distmatrix with shape (286, 286)
length of dist matrix before filtering 286
length of dist matrix after filtering 270
Result has shape (270, 270)
setA (38, 38)
setA (5, 5)
setA (179, 179)
setA (154, 154)
setA (95, 95)
setA (119, 119)
setA (189, 189)
setA (10, 10)
setA (412, 412)
setA (453, 453)
Filtering 40 from distmatrix with shape (453, 453)
length of dist matrix before filtering 453
length of dist matrix after filtering 438
Result has shape (438, 438)
setA (149, 149)
Filtering 4 from distmatrix with shape (149, 149)
length of dist matrix before filtering 149
length of dist matrix after filtering 145
Result has shape (145, 145)
setA (252, 252)
setA (283, 283)
setA (322, 322)
Filtering 2 from distmatrix with shape (322, 322)
length of dist matrix before filtering 322
length of dist matrix after filtering 321
Result has shape (321, 321)
setA (178, 178)
setA (124, 124)
setA (342, 342)
setA (359, 359)
setA (56, 56)
setA (297, 297)
setA (30, 30)
setA (506, 506)
setA (234, 234)
Filtering 1 from distmatrix with shape (234, 234)
length of dist matrix before filtering 234
length of dist matrix after filtering 233
Result has shape (233, 233)
setA (35, 35)
setA (280, 280)
setA (85, 85)
setA (139, 139)
setA (286, 286)
setA (67, 67)
setA (77, 77)
setA (211, 211)
Filtering 132 from distmatrix with shape (211, 211)
length of dist matrix before filtering 211
length of dist matrix after filtering 211
Result has shape (211, 211)
setA (140, 140)
setA (54, 54)
setA (91, 91)
setA (304, 304)
setA (202, 202)
setA (79, 79)
setA (18, 18)
setA (173, 173)
setA (28, 28)
setA (87, 87)
setA (57, 57)
setA (364, 364)
setA (447, 447)
setA (264, 264)
setA (153, 153)
setA (323, 323)
setA (177, 177)
Filtering 13 from distmatrix with shape (177, 177)
length of dist matrix before filtering 177
length of dist matrix after filtering 164
Result has shape (164, 164)
setA (239, 239)
setA (156, 156)
setA (288, 288)
Filtering 13 from distmatrix with shape (288, 288)
length of dist matrix before filtering 288
length of dist matrix after filtering 288
Result has shape (288, 288)
setA (1202, 1202)
Filtering 3 from distmatrix with shape (1202, 1202)
length of dist matrix before filtering 1202
length of dist matrix after filtering 1199
Result has shape (1199, 1199)
setA (32, 32)
setA (160, 160)
setA (244, 244)
setA (95, 95)
setA (148, 148)
setA (276, 276)
setA (365, 365)
setA (265, 265)
setA (123, 123)
setA (124, 124)
setA (83, 83)
setA (318, 318)
setA (279, 279)
setA (349, 349)
setA (263, 263)
setA (207, 207)
setA (70, 70)
setA (84, 84)
setA (236, 236)
setA (221, 221)
setA (197, 197)
setA (568, 568)
Filtering 1 from distmatrix with shape (568, 568)
length of dist matrix before filtering 568
length of dist matrix after filtering 567
Result has shape (567, 567)
setA (344, 344)
setA (116, 116)
setA (400, 400)
setA (138, 138)
setA (79, 79)
setA (25, 25)
Filtering 4 from distmatrix with shape (25, 25)
length of dist matrix before filtering 25
length of dist matrix after filtering 21
Result has shape (21, 21)
setA (1, 1)
setA (51, 51)
setA (186, 186)
setA (57, 57)
setA (516, 516)
Filtering 5 from distmatrix with shape (516, 516)
length of dist matrix before filtering 516
length of dist matrix after filtering 516
Result has shape (516, 516)
setA (410, 410)
Filtering 3 from distmatrix with shape (410, 410)
length of dist matrix before filtering 410
length of dist matrix after filtering 410
Result has shape (410, 410)
setA (77, 77)
Filtering 2 from distmatrix with shape (77, 77)
length of dist matrix before filtering 77
length of dist matrix after filtering 77
Result has shape (77, 77)
setA (149, 149)
setA (79, 79)
setA (195, 195)
setA (370, 370)
setA (390, 390)

In [22]:
## Abbreviated version - just gets the length of hte already filtered distmaps, no filtering performed
all_hits["filtered_length"] = np.nan
excluded_ids = []

for idx, row in all_hits.iterrows():
    uid = row.uid
    entry = row.Entry

    
    if os.path.isfile(f"filtered_distmaps/{entry}.csv"):
        dm = DistanceMap.from_file(f"filtered_distmaps/{entry}")
        all_hits.loc[idx, "filtered_length"] = len(dm.residues_i)
        
    else:
        excluded_ids.append(uid)

## Clean up the protein hit table

In [23]:
all_hits = all_hits.query("not uid in @excluded_ids")
all_hits[["uid", "Entry", "rv",  "set", 'pdb_id', 'pdb_chain', 'filtered_length']].to_csv("summary_data/01.structure_hits.csv")

In [24]:
all_hits = pd.read_csv("summary_data/01.structure_hits.csv", index_col=0)
print(len(all_hits))
print(len(all_hits.query("not filtered_length < 30")))
all_hits.query("not filtered_length < 30").to_csv("summary_data/01.structure_hits_filtered.csv")

3758
3687

In [25]:
all_hits = pd.read_csv("summary_data/01.structure_hits_filtered.csv")

In [26]:
len(all_hits.query("set=='setA'")), len(all_hits.query("set=='setB'"))

(2337, 1350)

In [27]:
2337+1350

3687